<h2>Atividade 2 - Desenvolvimento de Sistemas de IA

Pietra Paz Lapa de Almeida Pinheiro | 22401571

**Tema:** Filtragem Colaborativa

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
url1 = "https://raw.githubusercontent.com/pietrapaz/dsia_dados/refs/heads/main/datasets/movies.csv"
url2 = "https://raw.githubusercontent.com/pietrapaz/dsia_dados/refs/heads/main/datasets/ratings.csv"

movies = pd.read_csv(url1)
ratings = pd.read_csv(url2)

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

#### Best-seller

In [ ]:
# media das notas de cada filme
melhores_avaliados = (
    ratings.groupby("movieId")["rating"]
    .mean()
    .reset_index(name="media_rating")
    .sort_values("media_rating", ascending=False)
)

In [ ]:
# adicionando titulo do filme
melhores_avaliados = melhores_avaliados.merge(
    movies[["movieId", "title"]],
    on="movieId"
)

In [ ]:
# organizando as colunas
melhores_avaliados = melhores_avaliados[
    ["movieId", "title", "media_rating"]
]

In [ ]:
print(melhores_avaliados.head(10))

   movieId                              title  media_rating
0   187717   Won't You Be My Neighbor? (2018)           5.0
1     6983                   Jane Eyre (1944)           5.0
2     5328                        Rain (2001)           5.0
3    95843             Goodbye Charlie (1964)           5.0
4     3941     Sorority House Massacre (1986)           5.0
5     3940  Slumber Party Massacre III (1990)           5.0
6     3939   Slumber Party Massacre II (1987)           5.0
7     7815                True Stories (1986)           5.0
8   162414                          Moonlight           5.0
9   162344  Tom Segura: Mostly Stories (2016)           5.0

#### Similaridade

In [ ]:
# criacao da tabela
matriz = ratings.pivot_table(
    index="movieId",
    columns="userId",
    values="rating",
    fill_value=0
)

In [ ]:
matriz.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,0.0,0.0,4.0,0.0,4.5,0.0,0.0,0.0,...,4.0,0.0,4.0,3.0,4.0,2.5,4.0,2.5,3.0,5.0
2,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,...,0.0,4.0,0.0,5.0,3.5,0.0,0.0,2.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
similaridade = cosine_similarity(matriz)

In [ ]:
print(similaridade)

[[1.         0.41056206 0.2969169  ... 0.         0.         0.        ]
 [0.41056206 1.         0.28243799 ... 0.         0.         0.        ]
 [0.2969169  0.28243799 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]