<h2>Atividade 1 - Desenvolvimento de Sistemas de IA

Pietra Paz Lapa de Almeida Pinheiro | 22401571

**Tema:** Filtragem

In [ ]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
url1 = "https://raw.githubusercontent.com/pietrapaz/dsia_dados/refs/heads/main/datasets/movies.csv"
url2 = "https://raw.githubusercontent.com/pietrapaz/dsia_dados/refs/heads/main/datasets/ratings.csv"

movies = pd.read_csv(url1)
ratings = pd.read_csv(url2)

In [ ]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [ ]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

### Best-seller

In [ ]:
# agrupando as avaliacoes pelo id do filme
best_sellers = (ratings.groupby("movieId").size().reset_index(name="qtd").sort_values("qtd", ascending=False))

In [ ]:
# juntando best sellers com a tabela de filmes
best_sellers = best_sellers.merge(movies[["movieId", "title"]], on="movieId")

In [ ]:
# colunas que serao visualizadas
best_sellers = best_sellers[["movieId", "title", "qtd"]]

In [ ]:
best_sellers.head(10)

   movieId                                      title  qtd
0      356                        Forrest Gump (1994)  329
1      318           Shawshank Redemption, The (1994)  317
2      296                        Pulp Fiction (1994)  307
3      593           Silence of the Lambs, The (1991)  279
4     2571                         Matrix, The (1999)  278
5      260  Star Wars: Episode IV - A New Hope (1977)  251
6      480                       Jurassic Park (1993)  238
7      110                          Braveheart (1995)  237
8      589          Terminator 2: Judgment Day (1991)  224
9      527                    Schindler's List (1993)  220

### Similaridade

In [ ]:
# avaliou o filme = 1; nao avaliou = 0
# criacao da tabela
matriz = (
    ratings.assign(interacao=1)
    .pivot_table(
        index="movieId",
        columns="userId",
        values="interacao",
        fill_value=0
    )
)

In [ ]:
similaridade = cosine_similarity(matriz)

In [ ]:
print(matriz.head())

userId   1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
movieId                                                    ...
1        1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  1.0
2        0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  ...  0.0  1.0  0.0
3        1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
5        0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

userId   604  605  606  607  608  609  610
movieId
1        1.0  1.0  1.0  1.0  1.0  1.0  1.0
2        1.0  1.0  0.0  0.0  1.0  0.0  0.0
3        0.0  0.0  0.0  0.0  1.0  0.0  0.0
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0
5        1.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 610 columns]